language: node_js

node_js:
  - node

dist: trusty
sudo: false
 
addons:
  apt:
    packages:
      - google-chrome-stable
 
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

env:
  - TEST_DIR=node-demo
  - TEST_DIR=angular2-demo

script: cd $TEST_DIR && npm install && npm test
